services:
      db:
            restart: always
            container_name: postgres
            image: postgres
            environment:
                  -  POSTGRES_USER=avimehta
                  -  POSTGRES_PASSWORD=12345678
            volumes:
                  - ./postgres-data:/var/lib/postgresql/data
                  - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
            ports:
                  - '5432:5432'